### ISSUE TITLE
ディレクトリの構成の見直し、および、不要なファイルを削除

### ISSUE THREAD

**Issue by iHalt10** [prog-nori/java-utility#1]
現在
```
.
├─ Makefile
├─ build.xml
├─ classes/
├─ docs/
├─ documents/
├─ example/
├─ ren.txt
├─ utility/
├─ utility.jar
└─ utility.mf
```

**Comment by iHalt10** [comment]
コミットに入れない方が良いファイルたち
- classes/
  - classファイルはバイナリであり、肥大化するおそれと、差分がわかりにくくなるため
- docs/ and documents/
  -  java docは、コミットに入れず、リリース(v0.0.0のときなど)にリリースフォルダに入れる
- utility.jar
  - リリースフォルダに入れる

**Comment by prog-nori** [comment]
除去完了。ありがとう！
